server:
  port: 8083
  servlet:
    session:
      cookie:
        name: oauth2login
spring:
  security:
    oauth2:
      client:
        registration:
          oauth2-login:
            provider: oauth2-login
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/client"
        provider:
          oauth2-login:
            authorization-uri: http://localhost:8081/oauth/authorize
            token-uri: http://localhost:8081/oauth/token
            user-info-uri: http://localhost:8082/user/me
            user-name-attribute: name

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
